# Generated by Django 5.2.5 on 2025-09-22 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_rename_datefabrication_produit_datefabprod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_rayon', to='monApp.rayon'),
        ),
    ]
